server:
  port: 8888
spring:
  application:
    name: eureka-server
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://127.0.0.1:${server.port}/eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false